export const PRIVATE = '/'
export const PUBLIC = '/portal'
export const NOT_FOUND = '/*'

export const JEFATURA_PIURA = '/jefatura-piura'
export const CONTROL_MIGRATORIO = '/control-migratorio'
export const TRAMITE_INMIGRACION = '/tramite-inmigracion'
export const TRAMITE_NACIONALIZACION = '/tramite_nacionalizacion'
export const PASAPORTES = '/pasaportes'
export const CITAS = '/citas'
export const ALERTAS = '/alertas'
