export * from './create-regla-negocio.service'
export * from './delete-regla-negocio.service'
export * from './find-all-dimension.service'
export * from './find-all-hallazgos-by-paginacion.service'
export * from './find-by-proceso.service'
export * from './find-regla-negocio-by-id.service'
export * from './modify-regla-negocio.service'
