export * from './find-all-dimension.service'
export * from './find-all-hallazgos-by-paginacion.service'
export * from './find-by-id.service'
export * from './find-by-proceso.service'
export * from './get-metrica-datos-invalidos-jz.service'
export * from './get-metrica-dependencia-jz.service'
export * from './get-metrica-operador-jz.service'
export * from './get-metrica-resumen-jz.service'
