export * from './data-response.interface'
export * from './header-response.interface'
export * from './local-storage.d'
export * from './message-type.interface'
export * from './proceso.interface'
export * from './regla-negocio.interface'
export * from './usuario.interface'
